# Generated by Django 5.2.6 on 2026-02-03 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
        ('profiles', '0002_profiles_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='author.author'),
        ),
    ]
