# Generated by Django 5.2.6 on 2026-01-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('roll', models.IntegerField(primary_key=True, serialize=False)),
                ('father_name', models.CharField(max_length=30)),
                ('adresss', models.TextField()),
            ],
        ),
    ]
