# Generated by Django 5.2.6 on 2026-02-03 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categories',
            new_name='Category',
        ),
    ]
